INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.02 FOC20K',N'BK COPY + PRINT A4 & A3 FOC 20000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.02 FOC7.5K',N'BK COPY + PRINT A4 & A3 FOC 7500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.0237 FOC3K',N'BK COPY + PRINT A4 & A3 FOC 3000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.0242 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.025 FOC20K',N'BK COPY + PRINT A4 & A3 FOC 20000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.027 FOC10K',N'BK COPY + PRINT A4 & A3 FOC 10000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.027 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.027 FOC800',N'BK COPY + PRINT A4 & A3 FOC 800PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.0271 FOC3K',N'BK COPY + PRINT A4 & A3 FOC 3000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.028 FOC300',N'BK COPY + PRINT A4 & A3 FOC 300PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.0285 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK +P - 0.0285 FOC3K',N'BK COPY + PRINT A4 & A3 FOC 3000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.022 FOC5K',N'BK COPY + PRINT A4 & A3 FOC 5000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.025 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.025 FOC2K',N'BK COPY + PRINT A4 & A3 FOC 2000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.025 FOC3K',N'BK COPY + PRINT A4 & A3 FOC 3000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.025 FOC7K',N'BK COPY + PRINT A4 & A3 FOC 7000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.025 FOC8K',N'BK COPY + PRINT A4 & A3 FOC 8000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.02FOC 3K',N'BK COPY + PRINT A4 & A3 FOC 3000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.02FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.02FOC2.5K',N'BK COPY + PRINT A4 & A3 FOC 2500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.03 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.03 FOC2K',N'BK COPY + PRINT A4 & A3 FOC 2000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.03 FOC333',N'BK COPY + PRINT A4 & A3 FOC 333PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.03 FOC500',N'BK COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.03 FOC700',N'BK COPY + PRINT A4 & A3 FOC 700PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.03FOC10K',N'BK COPY + PRINT A4 & A3 FOC 10000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.04 FOC100',N'BK COPY + PRINT A4 & A3 FOC 100PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.04 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.04 FOC400',N'BK COPY + PRINT A4 & A3 FOC 400PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P - 0.04 FOC500',N'BK COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.005 FOC25K',N'BK COPY + PRINT A4 & A3 FOC 25000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.025 FOC10K',N'BK COPY + PRINT A4 & A3 FOC 10000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.025 FOC500',N'BK COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.025FOC1.5K',N'BK COPY + PRINT A4 & A3 FOC 1500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.025FOC2.5K',N'BK COPY + PRINT A4 & A3 FOC 2500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.025FOC2K',N'BK COPY + PRINT A4 & A3 FOC 2000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P -0.03 FOC4K',N'BK COPY + PRINT A4 & A3 FOC 4000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P- .02 FOC10K',N'BK COPY + PRINT A4 & A3 FOC 10000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P- 0.025 FOC1.2',N'BK COPY + PRINT A4 & A3 FOC 1200PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC1.2K',N'BK COPY + PRINT A4 & A3 FOC 1200PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC1.5K',N'BK COPY + PRINT A4 & A3 FOC 1500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC10K',N'BK COPY + PRINT A4 & A3 FOC 10000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC2K',N'BK COPY + PRINT A4 & A3 FOC 2000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC3K',N'BK COPY + PRINT A4 & A3 FOC 3000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC500',N'BK COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.028 FOC5K',N'BK COPY + PRINT A4 & A3 FOC 5000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.029 FOC1K',N'BK COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.0297 FOC4K',N'BK COPY + PRINT A4 & A3 FOC 4000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.03 FOC1.5K',N'BK COPY + PRINT A4 & A3 FOC 1500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK C+P-0.03 FOC5K',N'BK COPY + PRINT A4 & A3 FOC 5000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'BK+P - 0.0242 FOC500',N'BK COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C +P - 0.291 FOC500',N'CL COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C +P - 0.70 FOC 1K',N'COPY + PRINT FOC 1000M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C +P - 0.80 FOC300',N'COPY + PRINT FOC 300M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C +P - 0.80 FOC375',N'COPY + PRINT A4 & A3 FOC 375M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C+P - 1.00',N'COPY + PRINT A4 & A3',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C+P - 1.00 FOC300',N'COPY + PRINT A4 & A3 FOC 300M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C+P - 1.10 FOC319',N'COPY + PRINT A4 & A3 FOC 319M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'C+P - 1.20',N'COPY + PRINT A4 & A3 FOC 417M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR +P-0.285FOC500',N'COLOR COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR +P-0.40 FOC100',N'COLOR COPY + PRINT A4 & A3 FOC 100PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.297FOC1K',N'COLOR COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.34FOC500',N'COLOR COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.35FOC100',N'COLOR COPY + PRINT A4 & A3 FOC 100PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.35FOC320',N'COLOR COPY + PRINT A4 & A3 FOC 320PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.35FOC500',N'COLOR COPY + PRINT A4 & A3 FOC 500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.3FOC1K',N'COLOR COPY + PRINT A4 & A3 FOC 1000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.40 FOC20',N'COLOR COPY + PRINT A4 & A3 FOC 20PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.40 FOC30',N'COLOR COPY + PRINT A4 & A3 FOC 30PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.40 FOC50',N'COLOR COPY + PRINT A4 & A3 FOC 50PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.45 FOC10',N'COLOR COPY + PRINT A4 & A3 FOC10PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.45 FOC20',N'COLOR COPY + PRINT A4 & A3 FOC20PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.45FOC100',N'COLOR COPY + PRINT A4 & A3 FOC 100PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.50 FOC10',N'COLOR COPY + PRINT A4 & A3 FOC 10PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR C+P-0.50 FOC20',N'COLOR COPY + PRINT A4 & A3 FOC 20PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR+P-0.05FOC12.5K',N'COLOR COPY + PRINT A4 & A3 FOC 12500PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR+P-0.05FOC20K',N'COLOR COPY + PRINT A4 & A3 FOC 20000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COLOR+P-0.10FOC12K',N'COLOR COPY + PRINT A4 & A3 FOC 12000PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'COPY+PRINT FOC100',N'COPY + PRINT A1 FOC 100PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'IMPORT',N'TEST MULTI',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'MONTHLY RENTAL',N'METER CHARGES < RM 100',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'MONTHLY RENTAL-WAIVE',N'METER CHARGES < RM 100',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'MR-WAIVE RM1000',N'METER CHARGES < RM 1000',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 0.90 FOC333',N'COPY + PRINT -meter',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 0.90 FOC334',N'COPY + PRINT -meter FOC 334M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 0.90 FOC389',N'COPY + PRINT FOC 389M',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 1.00 FOC1000',N'COPY + PRINT-meter',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 1.10 FOC300',N'COPY + PRINT-meter',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 1.20 FOC300',N'COPY + PRINT -meter',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 3.00 FOC 300PCS',N'COPY + PRINT-meter',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 3.00 FOC8K',N'COPY + PRINT A4/8PCS',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'PLO- 3.60 FOC100',N'COPY + PRINT- FOC 100',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'RM 488 BK',N'BK COPY + PRINT A4 & A3 UNLIMITED',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'RM 488 CL 0.35',N'COLOR COPY + PRINT A4 & A3',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'RM 488 CL 0.40',N'COLOR COPY + PRINT A4 & A3',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'RM 588 BK',N'BK COPY + PRINT A4 & A3 UNLIMITED',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'RM 588 CL 0.40',N'COLOR COPY + PRINT A4 & A3',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'RM 688 CL 0.45',N'COLOR COPY + PRINT A4 & A3',GETDATE());
INSERT INTO [dbo].[zSCP_MeterMultiPrice](MeterMultiPriceCode,[Description],LastModified) VALUES(N'testing',N'testing',GETDATE());
